# Configure requires $PTII
env:
  matrix:
    # Run separate jobs with these variables.  The name of the
    # variable corresponds with the target name in $PTII/build.xml and
    # should be alphabetical.
    - PT_TRAVIS_BUILD_ALL=true
    - PT_TRAVIS_DOCS=true
    - PT_TRAVIS_INSTALLERS=true
    # - PT_TRAVIS_PRIME_INSTALLER=true
    - PT_TRAVIS_TEST_CAPECODE_XML=true
    - PT_TRAVIS_TEST_REPORT_SHORT=true
  global:
    # Environment variables shared between all builds(in alphabetical order)

    - ANT_OPTS=-Xmx1024m
    - BCVTB_HOME=${TRAVIS_BUILD_DIR}/lbnl
    - LD_LIBRARY_PATH=/usr/lib/jni:/usr/local/share/OpenCV/java/:/usr/share/OpenCV/java:${LD_LIBRARY_PATH}
    - PT_NO_NET=true
    - PATH=${PTII}/bin:${PATH}
    - PTII=${TRAVIS_BUILD_DIR}
    - TRAVIS_TAG=nightly

language: node_js

# Node 8 breaks npm horribly, see http://www.accessors.org/wiki/Notes/Npm5
node_js:
  - "7"

# Need X11 to create the DOP Center map and for testing.
before_install:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

install:
  # We keep logs in a directory to avoid the 10k line problem.
  - mkdir -p $PTII/logs $PTII/reports/junit
  - echo $HOME
  - echo "Created by Travis-ci" > $HOME/README.md
  - ls -l $HOME
  
  # Shorter running installations first.

  # Below are the packages that are needed, in alphabetical order:
  #   genisoimage for building Darwin dmg files under Linux.
  #   Java3D
  #   libv4l for  Bridj for the camera.
  #   p7zip-full for installing jogl as part of the installers.
  #   pdflatex for the DOP Center image.
  - sudo apt-get install -y genisoimage libjava3d-java libv4l-dev p7zip-full texlive-latex-base || true

  # Install JAI.  If the wget fails, then don't stop the build.
  - if [ ! -f $PTII/vendors/jai-1_1_2_01/lib/jai_core.jar ]; then wget --quiet --no-cookies --header Cookie:\ oraclelicense=accept-securebackup-cookie http://download.oracle.com/otn-pub/java/jai/1.1.2_01-fcs/jai-1_1_2_01-lib-linux-i586.tar.gz -O /tmp/jai.tar.gz || true; if [ -f /tmp/jai.tar.gz ] ; then (cd vendors; tar -zxvf /tmp/jai.tar.gz) fi; fi

  # Install JMF.  If the wget fails, then don't stop the build.
  - ls $PTII/vendors/JMF-2.1.1e || true
  - if [ ! -f $PTII/vendors/JMF-2.1.1e/lib/jmf.jar ]; then wget --quiet --no-cookies --header Cookie:\ oraclelicense=accept-securebackup-cookie http://download.oracle.com/otn-pub/java/jmf/2.1.1e/jmf-2_1_1e-alljava.zip -O /tmp/jmf.zip || true; if [ -f /tmp/jmf.zip ] ; then (cd vendors; unzip /tmp/jmf.zip) fi; fi

  # Install Sphinx for the speech recognition accessor
  - if [ ! -d $PTII/vendors/misc/sphinx4 ]; then mkdir $PTII/vendors/misc/sphinx4; fi
  - if [ ! -f $PTII/vendors/misc/sphinx4/sphinx4-core-5prealpha.jar ]; then wget --quiet -O $PTII/vendors/misc/sphinx4/sphinx4-core-5prealpha.jar 'https://oss.sonatype.org/service/local/artifact/maven/redirect?r=releases&g=net.sf.phat&a=sphinx4-core&v=5prealpha&e=jar' || true; fi
  - if [ ! -f $PTII/vendors/misc/sphinx4/sphinx4-data-5prealpha.jar ]; then wget --quiet -O $PTII/vendors/misc/sphinx4/sphinx4-data-5prealpha.jar 'https://oss.sonatype.org/service/local/artifact/maven/redirect?r=releases&g=net.sf.phat&a=sphinx4-data&v=5prealpha&e=jar' || true; fi

  # Needed for building installers.
  - sudo ln -s /bin/tar /usr/local/bin/tar

  # Longer running installations:

  # Use the Travis cache, see https://docs.travis-ci.com/user/cachingp
  - sudo -E $PTII/org/ptolemy/opencv/travis_build_opencv.sh

  # List the contents of vendors and cached directories
  - ls $PTII/vendors
  - ls -l $PTII/vendors/adm/gen-11.0/node || true
  - ls -l $PTII/vendors/installer || true
  - ls -l $PTII/vendors/jai-1_1_2_01 || true
  - ls -l $PTII/vendors/JMF-2.1.1e || true
  - ls -l $PTII/vendors/jogl || true
  - ls -l $PTII/vendors/misc/sphinx4 || true
  - ls -l $PTII/vendors/opencv || true
  - ls -l $PTII/vendors/opencv/share/OpenCV/java || true

  # Display environment variables
  - env | sort
  - ./configure --enable-verbose

script:
  - ant clean >& $PTII/logs/ant_clean.txt
 
  # travis_wait does not help here because we want to redirect the output of cmake.
  # See https://github.com/travis-ci/travis-ci/issues/4190
  - while sleep 9m; do echo "=====[ $SECONDS seconds still running ]====="; done &

  - echo "About to call ptIITravisBuild.sh at $SECONDS seconds."
  - $PTII/bin/ptIITravisBuild.sh

  # Killing background sleep loop.
  - kill %1


# See https://docs.travis-ci.com/user/caching
cache:
  directories:
    - $PTII/vendors/adm/gen-11.0/node
    - $PTII/vendors/installer
    - $PTII/vendors/jai-1_1_2_01
    - $PTII/vendors/JMF-2.1.1e
    - $PTII/vendors/jogl
    - $PTII/vendors/misc/sphinx4
    - $PTII/vendors/opencv

# before_deploy:
#   # Set up git user name and tag this commit
#   - git config --local user.name "cxbrooks"
#   - git config --local user.email "cxh@eecs.berkeley.edu"
#   #  - git tag "$(date +'%Y%m%d%H%M%S')-$(git log --format=%h -1)"
#   - git tag nightly || true
#   - git push origin --tags https://${GITHUB_TOKEN}@github.com/icyphy/ptII || true
#   - echo $PTII
#   - ls -l $PTII/logs
#   - pwd
  
deploy:
  # - provider: pages
  #   github-token: $GITHUB_TOKEN  # Set in travis-ci.org dashboard, marked secure
  #   # local-dir is relative to the current directory
  #   local-dir: logs   
  #   keep-history: true
  #   on:
  #     branch: master
  #   skip-cleanup: true
  #   verbose: true
  - provider: releases
    api_key: $GITHUB_TOKEN
    file_glob: true
    file:
      - $PTII/adm/gen-11.0/capecode0.2.devel.setup.linux.tar.gz
      - $PTII/adm/gen-11.0/capecode0.2.devel.setup.mac.app.tar.gz
      - $PTII/adm/gen-11.0/capecode0_2_devel_setup_windows_64.exe
      - $PTII/adm/gen-11.0/ptII11.0.devel.setup.linux.tar.gz
      - $PTII/adm/gen-11.0/ptII11.0.devel.setup.mac.app.tar.gz
      - $PTII/adm/gen-11.0/ptII11_0_devel_setup_windows_64.exe
      - $PTII/adm/gen-11.0/ptII11_0_devel_setup_windows.exe
      - $PTII/adm/gen-11.0/ptII11.0.devel.src.tar
      - $PTII/adm/gen-11.0/ptII11.0.devel.src.zip
    on:
      tags: true
      condition: $PT_TRAVIS_INSTALLERS = true
    overwrite: true
    skip_cleanup: true    
    verbose: true
  # Update 
  - provider: releases
    api_key: $GITHUB_TOKEN
    file_glob: true
    file:
      - $PTII/doc/codeDoc*.jar
    on:
      tags: true
      condition: $PT_TRAVIS_DOCS = true
    overwrite: true
    skip_cleanup: true    
    verbose: true

notifications:
  email:
    recipients:
      - cxh@eecs.berkeley.edu
    on_success: always # default: change
    on_failure: always # default: always
