# Configure requires $PTII
env:
  global:
    - ANT_OPTS=-Xmx1024m
    - BCVTB_HOME=${TRAVIS_BUILD_DIR}/lbnl
    - PATH=${TRAVIS_BUILD_DIR)/bin:${PATH}
    - PT_NO_NET=true
    - TOSROOT=${TRAVIS_BUILD_DIR}/vendors/ptinyos/tinyos-1.x
    - TOSDIR=${TRAVIS_BUILD_DIR}/vendors/ptinyos/tinyos-1.x/tos
    - PATH=${PTII}/bin:${PATH}
    - PTINYOS_MOMLROOT=${TRAVIS_BUILD_DIR}/vendors/ptinyos/moml
    - PTII=${TRAVIS_BUILD_DIR}

language: node_js

# Node 8 breaks npm horribly, see http://www.accessors.org/wiki/Notes/Npm5
node_js:
  - "7"

install: ./configure

script: ant clean build-all javadoc jsdoc


